In [2]:

import numpy as np



In [24]:
np.random.seed(0)
W = np.random.randint(-9,9,size=(4,8))

np.random.seed(1)
X =  np.random.randint(-9,9,size=(5,4))

print(W,X)

C = np.dot(X,W)

print(C)

[[ 3  6 -9 -6 -6 -2  0 -5]
 [-3  3 -8 -3 -2  5  8 -4]
 [ 4 -1  0  7 -4  6  6 -9]
 [-6  8  5 -2 -9 -8  0 -9]] [[-4  2  3 -1]
 [ 0  2 -4  6]
 [-9  7 -8  3]
 [-2  4 -3 -4]
 [ 2  1  5 -5]]
[[  0 -29  15  41  17  44  34  -6]
 [-58  58  14 -46 -42 -62  -8 -26]
 [-98  -1  40 -29  45 -19   8  62]
 [ -6 -29 -34 -13  52  38  14  57]
 [ 53 -30 -51  30  11  71  38 -14]]


In [28]:
c_mask = C > 0
print(c_mask)

D = C * (C > 0)
print(D)

[[False False  True  True  True  True  True False]
 [False  True  True False False False False False]
 [False False  True False  True False  True  True]
 [False False False False  True  True  True  True]
 [ True False False  True  True  True  True False]]
[[ 0  0 15 41 17 44 34  0]
 [ 0 58 14  0  0  0  0  0]
 [ 0  0 40  0 45  0  8 62]
 [ 0  0  0  0 52 38 14 57]
 [53  0  0 30 11 71 38  0]]


In [29]:
D -= np.max(D,1,keepdims=True)
print(D)

[[-44 -44 -29  -3 -27   0 -10 -44]
 [-58   0 -44 -58 -58 -58 -58 -58]
 [-62 -62 -22 -62 -17 -62 -54   0]
 [-57 -57 -57 -57  -5 -19 -43   0]
 [-18 -71 -71 -41 -60   0 -33 -71]]


In [ ]:
c = np.random.randint()