In [1]:
import numpy as np


In [4]:
print(list(range(1,5)))
      

[1, 2, 3, 4]


In [5]:
for i in reversed(range(1,5)):
    print(i)

4
3
2
1


In [27]:
mask = np.ones((5,5),int)
print(mask)

p  = 0.5

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
J = np.random.rand(5,5)
print(J)
mask[J>p]  = 0
print(mask)

[[ 0.37213945  0.54122788  0.46913057  0.96299622  0.81282687]
 [ 0.05232892  0.77356554  0.3060964   0.86800447  0.29497724]
 [ 0.46589858  0.06460549  0.0176244   0.27214408  0.49507939]
 [ 0.54625812  0.73862959  0.90176031  0.89967407  0.96439404]
 [ 0.36929665  0.53759524  0.63046116  0.70071448  0.13970553]]


IndexError: too many indices for array

In [28]:
? np.random.rand

In [30]:
print(list(i for i in range(0,5)))

[0, 1, 2, 3, 4]


In [37]:
x = np.random.rand(5,5)
print(x)

[[ 0.99581344  0.19985237  0.02030465  0.78158778  0.39359223]
 [ 0.95155553  0.97794397  0.58206224  0.40956358  0.52010294]
 [ 0.3197488   0.29090417  0.73355701  0.43826129  0.90961165]
 [ 0.83492783  0.54515249  0.77757737  0.36077433  0.59320483]
 [ 0.76627175  0.96780413  0.41344899  0.61034052  0.00686944]]


In [38]:
np.random.rand(*x.shape)

array([[ 0.30386009,  0.78542099,  0.36607914,  0.64017058,  0.89775738],
       [ 0.56737512,  0.12646045,  0.05371383,  0.98934953,  0.29793252],
       [ 0.82288468,  0.87858149,  0.43528868,  0.28738754,  0.16721125],
       [ 0.50152072,  0.04020251,  0.41497936,  0.42097069,  0.97209743],
       [ 0.45919572,  0.0597507 ,  0.84474991,  0.95194424,  0.72474788]])

In [39]:
print(*x.shape)

5 5
