In [2]:
import numpy as np


In [3]:
a = np.random.randn(2,3,4,5)


[[[-0.12936273  0.03414432 -0.43142795 -0.93239771 -0.6468184 ]
  [-0.05956017 -0.19433691 -0.2300829   0.26941382 -0.39662214]
  [ 0.92679289  0.73179236  0.56531548 -0.8964827   0.58027258]
  [-0.22073116 -0.19593607  0.27122106 -0.92636818  0.19172752]]

 [[ 0.2974577  -0.11254188 -0.84204969  0.44456656  0.51301733]
  [-0.07048611  0.83690996  1.96278642  0.23998679 -0.33240664]
  [-0.98967131  0.58445867  1.31377064 -0.47925357 -0.12470899]
  [-0.36294655  0.2560301  -0.06184156 -0.47804009  0.01365952]]]


In [6]:
print(np.mean(a,axis=0).shape)

(3, 4, 5)


In [7]:
? np.zeros

In [8]:
? np.reshape