In [1]:
import numpy as np
import random.Random as rand

In [22]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [31]:
x.shape

(2, 4, 5, 6)

In [36]:
a = 1
for k in x.shape[1:]:
    a *= k
a
xx = x.reshape(2,a)
print(x.reshape(2,a).shape)

(2, 120)


In [44]:
x = np.linspace(-0.5, 0.5, num=12).reshape(3, 4)
x = np.maximum(0,x)

y = x * [x > 0]
y

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.04545455,  0.13636364],
        [ 0.22727273,  0.31818182,  0.40909091,  0.5       ]]])

In [18]:
? np.multiply

In [5]:
?np.random.randn

In [7]:
input_dim=3*32*32 
hidden_dim=100
num_classes=10
weight_scale=1e-3

W1 = weight_scale*np.random.randn(input_dim,hidden_dim)
b1 = np.zeros(hidden_dim)
W2 = weight_scale*np.random.randn(hidden_dim,num_classes)
b2 = np.zeros(num_classes)


array([[-0.00112839,  0.00117883, -0.00062077, ..., -0.00141543,
        -0.00099226, -0.00074327],
       [ 0.00071837,  0.00093135, -0.00061275, ...,  0.00080786,
         0.00078979, -0.00102252],
       [-0.00037729, -0.0003042 ,  0.00120269, ...,  0.00076969,
        -0.00076243, -0.00070643],
       ..., 
       [-0.00063786,  0.00047936, -0.00112482, ..., -0.00124411,
         0.00013677, -0.00033421],
       [ 0.00021886,  0.0021478 , -0.00134265, ...,  0.00132559,
         0.00079304, -0.0003057 ],
       [ 0.00014655, -0.00112367,  0.00069426, ...,  0.00078385,
        -0.00030067, -0.00019286]])

In [8]:
hidden_dims = [10,20]

for i+1,h in enumerate(hidden_dims):
    print(i,h)
    
weight = 'W'+str(i)
print(weight)

SyntaxError: can't assign to operator (<ipython-input-8-624cf6114dfa>, line 3)

In [18]:
np.random.seed(231)
x = np.random.randn(10,1)
print(x)
mean = np.mean(x)

var = np.std(x)
print(mean,var)

x = (x-mean)/var
print(x,np.mean(x),np.var(x))


[[ 0.41794341]
 [ 1.39710028]
 [-1.78590431]
 [-0.70882773]
 [-0.07472532]
 [-0.77501677]
 [-0.1497979 ]
 [ 1.86172902]
 [-1.4255293 ]
 [-0.3763567 ]]
-0.161938531569 1.08741451827
[[ 0.53326669]
 [ 1.4337116 ]
 [-1.49341925]
 [-0.50292615]
 [ 0.08020236]
 [-0.56379442]
 [ 0.01116467]
 [ 1.86099001]
 [-1.16201388]
 [-0.19718163]] -2.49800180541e-17 1.0


In [1]:
import numpy as np

In [4]:
x = np.random.randn(5)
x

array([-0.70523466,  0.68274215, -2.20316384,  0.63996409,  0.75092742])

In [5]:
x.reshape(5,

ValueError: cannot reshape array of size 5 into shape (5,5)

In [12]:
a = np.ones((5,5))
print(a)
b = x*a
print(b)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[-0.70523466  0.68274215 -2.20316384  0.63996409  0.75092742]
 [-0.70523466  0.68274215 -2.20316384  0.63996409  0.75092742]
 [-0.70523466  0.68274215 -2.20316384  0.63996409  0.75092742]
 [-0.70523466  0.68274215 -2.20316384  0.63996409  0.75092742]
 [-0.70523466  0.68274215 -2.20316384  0.63996409  0.75092742]]


In [11]:
? np.ones