In [1]:
import numpy as np


In [16]:
x_shape = (2, 3, 4, 4)
w_shape = (3, 3, 4, 4)
x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
w = np.linspace(-0.2, 0.3, num=np.prod(w_shape)).reshape(w_shape)
b = np.linspace(-0.1, 0.2, num=3)

In [17]:
print(x_shape,w_shape)

(2, 3, 4, 4) (3, 3, 4, 4)


In [32]:
pad = 1
stride = 2

N = 2
C = 3
Y = np.zeros(shape=(N,C,4+2*pad,4+2*pad))
print(Y.shape)

(2, 3, 6, 6)


In [35]:
for n in range(0,N):
    for c in range(0,C):
        y = np.pad(x[n,c,:,:],pad,'constant')
        Y[n,c,:,:] = y

print(Y.shape)        
print(x.shape)
print('Shape must be 2,3,6,6')


(2, 3, 6, 6)
(2, 3, 4, 4)
Shape must be 2,3,6,6


In [47]:
W = np.random.rand(5,5)
print(W)

X = np.random.rand(5,5)
print(X)

[[ 0.52487828  0.72677854  0.07310091  0.33556952  0.51855713]
 [ 0.24125956  0.76495531  0.98795402  0.09366077  0.21351593]
 [ 0.08796527  0.11151965  0.58649138  0.60633281  0.30680243]
 [ 0.72276126  0.48601319  0.04405596  0.9324512   0.35564974]
 [ 0.76030702  0.40622066  0.68402075  0.57205811  0.27614941]]
[[ 0.57178188  0.6608494   0.50134199  0.65555765  0.09876347]
 [ 0.4147175   0.62794953  0.70089168  0.6667082   0.19994701]
 [ 0.50253143  0.9923717   0.57119178  0.82231152  0.94969716]
 [ 0.0152182   0.36914558  0.34868258  0.2580815   0.65786336]
 [ 0.64627115  0.51952609  0.06230337  0.67888538  0.51385419]]


In [50]:
Z = W*X
print(X)

[[ 0.57178188  0.6608494   0.50134199  0.65555765  0.09876347]
 [ 0.4147175   0.62794953  0.70089168  0.6667082   0.19994701]
 [ 0.50253143  0.9923717   0.57119178  0.82231152  0.94969716]
 [ 0.0152182   0.36914558  0.34868258  0.2580815   0.65786336]
 [ 0.64627115  0.51952609  0.06230337  0.67888538  0.51385419]]


In [52]:
print(np.sum(Z))

5.70175893401


In [53]:
? np.sum